### ISSUE TITLE
Game broken

### ISSUE THREAD

**Issue by githubteacher** [githubschool/github-games-gsuzor91#1]
When attempting to access this at https://githubschool.github.io/github-games-gsuzor91/, I am getting a 404. This could be caused by a couple things:

 - GitHub pages needs to be enabled on main. You can fix this in the repository settings.
- the index.html file is incorrectly named inde.html. We will fix this together in class.

 Can you please fix the first bullet @gsuzor91?

**Comment by gsuzor91** [comment]
The first bullet was fixed by going to Settings > GitHub Pages and setting `Branch: main` `/(root)`

![image](https://user-images.githubusercontent.com/70114729/104744048-67f7ee80-571a-11eb-9f55-1cd1427d4427.png)

**Comment by gsuzor91** [comment]
Reverted f99c to fix this issue.
